relative_permalinks: true
markdown: kramdown
title: Hands-on Exercises
exclude: [README.md, tachyon.md, blinkdb.md, logging-into-the-cluster.md, overview-of-the-exercises.md, introduction-to-the-scala-shell.md, data-exploration-using-spark.md, where-to-go-from-here.md, less]
organizers-email: "training-organizers@spark-summit.org"
